general {
  lock_cmd = pidof hyprlock || hyprlock								# Avoid running multiple sessions of hyprlock
  unlock_cmd = notify-send -a "hyprlock" -t 5000 -u low -i unlock "Welcome back, $USER\!"	# Welcome back
  before_sleep_cmd = loginctl lock-session							# Lock before suspend
  after_sleep_cmd = hyprctl dispatch dpms on							# Avoid pressing key twice to turn display on
}

listener {
  timeout = 120											# 2 Minutes
  on-timeout = brightnessctl -sd platform::kbd_backlight s 0					# Turn off keyboard backlight
  on-resume = brightnessctl -rd platform::kbd_backlight						# Restore keyboard backlight
}

listener {
  timeout = 180											# 3 Minutes
  on-timeout = brightnessctl -s set 10								# Dim screen
  on-resume = brightnessctl -r									# Restore brightness
}

listener {
  timeout = 300											# 5 Minutes
  on-timeout = loginctl lock-session								# Lock session
}

listener {
  timeout = 600											# 10 Minutes
  on-timeout = hyprctl dispatch dpms off							# Turn screen off
  on-resume = hyprctl dispatch dpms on								# Turn screen on
}

listener {
  timeout = 900											# 15 Minutes
  on-timeout = systemctl suspend								# Suspend session
}
