# Monitors
monitor=,2560x1600@60,auto,auto

# Default Programs
$terminal = kitty
$fileManager = dolphin
$menu = rofi

# Env
env = XCURSOR_SIZE,32
env = QT_QPA_PLATFORMTHEME,qt6ct

# Input
input {
  kb_layout = de
  numlock_by_default = true


  follow_mouse = 1

  touchpad {
    disable_while_typing = true
    natural_scroll = true
    clickfinger_behavior = true
    tap-to-click = true
  }

  sensitivity = 0
}

# Gestures
gestures {
  workspace_swipe = true
  workspace_swipe_fingers = 3

}

# Misc
misc {
  disable_hyprland_logo = true
  disable_splash_rendering = true
  force_default_wallpaper = 0

}

# XWayland
xwayland {
  use_nearest_neighbor = true
  force_zero_scaling = true
}

# Window Rules
windowrulev2 = float,class:^(kitty)$,title:^(kitty)$ # Make kitty floating
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.
windowrulev2 = stayfocused,class:^(jetbrains-.*) # Fix jetbrains mouse misalignment (https://github.com/hyprwm/Hyprland/issues/4888)


# Use SUPER as main modifier
$mainMod = SUPER

# Keybinds

# Window Management
bind = $mainMod, C, exec, killactive # Close window
bind = $mainMod, T, exec, $terminal # Open terminal
bind = $mainMod, E, exec, $fileManager # Open file manager
bind = $mainMod, V, togglefloating, # Toggle floating
bind = $mainMod, R, exec, $menu # Open menu
bind = $mainMod, F, fullscreen, # Toggle fullscreen
bind = $mainMod, H, hcenter, # Center horizontally
bind = $mainMod, V, vcenter, # Center vertically
bind = $mainMod, M, maximize, # Maximize
bind = $mainMod, N, minimize, # Minimize

# Workspaces
# Switch to workspace
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move window to workspace
bind = $mainMod, Shift, 1, movewindow, 1
bind = $mainMod, Shift, 2, movewindow, 2
bind = $mainMod, Shift, 3, movewindow, 3
bind = $mainMod, Shift, 4, movewindow, 4
bind = $mainMod, Shift, 5, movewindow, 5
bind = $mainMod, Shift, 6, movewindow, 6
bind = $mainMod, Shift, 7, movewindow, 7
bind = $mainMod, Shift, 8, movewindow, 8
bind = $mainMod, Shift, 9, movewindow, 9
bind = $mainMod, Shift, 0, movewindow, 10

# Move window to next/previous workspace
bind = $mainMod, Shift, Left, movewindow, prev
bind = $mainMod, Shift, Right, movewindow, next

# Move window to next/previous monitor
bind = $mainMod, Shift, Up, movewindow, prevmonitor
bind = $mainMod, Shift, Down, movewindow, nextmonitor

# Scroll through workspaces with mouse wheel
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move window with mouse
bind = $mainMod, Alt, mouse_left, movewindow
bind = $mainMod, Alt, mouse_right, resizewindow
